name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test with Node.js 16.14.2
    runs-on: [ ubuntu-22.04 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - name: npm install and test
        run: |
          npm install
          npm test